version: '3.1'

services:
  server:
    build:
      context: .
      target: final
    ports:
      - 6969:6969
    depends_on: 
      - redis
    networks:
      - redis-network 

  redis:
    container_name: reids-db
    image: redis:latest
    command: redis-server
    volumes:
      - redis:/var/lib/redis
    ports:
      - 6379:6379
    networks:
      - redis-network

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
    networks:
      - redis-network
    depends_on:
      - redis

volumes:
  redis:
  redis-config:

networks:
  redis-network:
    driver: bridge
